OrdererOrgs:
  - Name: OrderingService
    Domain: myNetwork.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: myPeer1
    Domain: peer1.myNetwork.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users: 
      Count: 1
      
  - Name: myPeer2
    Domain: peer2.myNetwork.com
    EnableNodeOUs: true
    Template:
      Count: 1

    Users: 
      Count: 1
